# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 641, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.hosts = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.hosts.setGeometry(QtCore.QRect(20, 120, 251, 391))
        self.hosts.setObjectName("hosts")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 90, 111, 21))
        self.label_2.setObjectName("label_2")
        self.rule_confirm = QtWidgets.QTextBrowser(self.centralwidget)
        self.rule_confirm.setGeometry(QtCore.QRect(310, 120, 351, 91))
        self.rule_confirm.setObjectName("rule_confirm")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 227, 361, 54))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.setpool = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.setpool.setToolTip("")
        self.setpool.setStatusTip("")
        self.setpool.setWhatsThis("")
        self.setpool.setMaxLength(2)
        self.setpool.setObjectName("setpool")
        self.gridLayout.addWidget(self.setpool, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 290, 111, 21))
        self.label_4.setObjectName("label_4")
        self.res_dir = QtWidgets.QTextBrowser(self.centralwidget)
        self.res_dir.setGeometry(QtCore.QRect(310, 320, 351, 91))
        self.res_dir.setObjectName("res_dir")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 470, 331, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 440, 111, 21))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(MainWindow.get_ip)
        self.pushButton.clicked.connect(MainWindow.get_rule)
        self.pushButton_3.clicked.connect(MainWindow.multiprocess_update)
        self.pushButton_2.clicked.connect(MainWindow.get_res_dir)
        self.setpool.editingFinished.connect(MainWindow.get_pool)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "raisecom iTN auto upgrader V1.0"))
        self.pushButton_4.setText(_translate("MainWindow", "载入设备ip表"))
        self.pushButton.setText(_translate("MainWindow", "载入规则文件"))
        self.pushButton_2.setText(_translate("MainWindow", "设置结果保存目录"))
        self.pushButton_3.setText(_translate("MainWindow", "批量升级"))
        self.label_2.setText(_translate("MainWindow", "已载入的规则文件："))
        self.label_3.setText(_translate("MainWindow", "设备ip列表："))
        self.label.setText(_translate("MainWindow", "输入并发进程数（不大于99）："))
        self.label_4.setText(_translate("MainWindow", "结果保存目录："))
        self.label_5.setText(_translate("MainWindow", "批量升级进度："))

